---
title: "Machine Learning"
subtitle: "Statistical Machine Learning--Stat 627"
author:
  - name: "Jithendra Sadu, Samuel Mweni, Wesley Wilson"
date: "23 Oct 2023"
format: 
  docx:
    reference-doc: custom-reference-doc.docx
editor: visual
engine: knitr
---

```{r, echo=FALSE, include=FALSE}
# source("data_analysis.R")
```

## Executive Summary

Something, something, something...

-   Identify relevant stakeholders

-   ethical concerns

## Research Question

What factors influence police stop outcomes in Washington, D.C., and what are their implications for community-police interactions?

## About the Data

<https://opendata.dc.gov/datasets/DCGIS::stop-data/about>

[https://www.arcgis.com/sharing/rest/content/items/cc1b18f4c6954ae891d2e262b991b06a/info/metadata/metadata.xml?format=default&output=htmlhttps://www.arcgis.com/sharing/rest/content/items/cc1b18f4c6954ae891d2e262b991b06a/info/metadata/metadata.xml?format=default&output=html](https://www.arcgis.com/sharing/rest/content/items/cc1b18f4c6954ae891d2e262b991b06a/info/metadata/metadata.xml?format=default&output=html)

The data includes additional information about the search for example, whether the person gave consent, there was a warrant involved, if the officer had probable cause, etcetera. For simplicity, I remove these attributes and instead focus on if a search was conducted.

### Data Challenges 

## Methodology

### What will the Outcome of my Stop Be?  

-   Build a classification model to predict the outcome a police stop (e.g., ticket, warning, arrest) based on various factors such a demographics, time of day, or stop duration.

-   Approach / methods

-   One plot

### Will I be Searched by the Police? 

-   Will I be searched by the police?: Build a binary classification model capable of predicting the likeliness of a police search based on various factors such as demographics, time of day, stop duration, etc.

-   Approach / methods

-   One plot

### How Long Will the Stop Last? 

-   Predicting stop duration: Build a model to predict how long a police stop might last once initiated.

-   Approach / methods

-   One plot

## Results

What we found.

## Summarized Findings

## Recommendations

-   Identify

{{< pagebreak >}}

## References

::: {#refs}
:::
